version: 2.1

jobs:
  build:
    executor:
      name: builder
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y gcc make curl patch
            curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-amd64.tar.gz | tar zx -C /tmp/
            sudo mv golangci-lint-1.31.0-linux-amd64/golangci-lint /usr/local/bin
      - run:
          name: Build kakasi static library
          command: make all
      - run:
          name: Run Tests
          command: go test
      - run:
          name: Linting
          command: make lint

workflows:
  version: 2
  test:
    jobs:
      - build

executors:
  builder:
    docker:
      - image: golang:1.16beta1-buster
